server:
  port: 9090

spring:
  application:
    name: microservice-course
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://bikqvkpcgq2zffhwi3ak-postgresql.services.clever-cloud.com:50013/bikqvkpcgq2zffhwi3ak?useSSL=false
    username: ukkjhcoyrrwyxq7vfj0s
    password: uTivRVoinDbMamIfEVZ94OdMQyyvWK
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
